### ISSUE TITLE
What is this project's license?

### ISSUE THREAD

**Issue by JordanMartinez** [dmbfm/purescript-tree#8]
@dmbfm What is the license for this repo? A number of people forked this repo and updated it to the `0.12.7` release. I've done the same and have further built upon it. However, I'm wondering about copyright issues.

**Comment by dmbfm** [comment]
Yeah, I never added a LICENSE file, but this is 100% free, public domain code. I haven't touched purescript in a while, so this is not maintained. Forks are more than welcome.

**Comment by JordanMartinez** [comment]
Ok. I'll refer to this comment then. Thanks!
