### ISSUE TITLE
Status of this repo? / License?

### ISSUE THREAD

**Issue by JordanMartinez** [dmbfm/purescript-tree#9]
@dmbfm I've noticed that there hasn't been any activity in quite some time. So, just curious. Is this project still active? Are you still maintaining it?

If not, could you please add a license to this repo? I'd like to make a few changes in a fork and continue development there.

**Comment by dmbfm** [comment]
I no longer maintain this, fell free to fork it.

**Comment by JordanMartinez** [comment]
Since this came up in Discord, I've forked this repo here: https://github.com/jordanmartinez/purescript-tree-rose
